workflows:
  time-sync:
    name: Build iOS & Android
    environment:
      flutter: stable
      vars:
        APP_IDENTIFIER: com.ili.gamb

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build Android APK
        script: flutter build apk --release

      - name: Build iOS IPA
        script: flutter build ipa --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - ilias.khayatelg@gmail.com
