name: gamb
description: A BLE Time-Sync & Data-Capture Demo App
version: 0.1.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.0.2
  path_provider: ^2.0.15
  csv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
